// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV2k4x5WsQkh6-kMjJmySJ185YFFM1afg',
    appId: '1:580119553329:web:f10e9beb3622e2e5657c10',
    messagingSenderId: '580119553329',
    projectId: 'salahtrackerbybasit',
    authDomain: 'salahtrackerbybasit.firebaseapp.com',
    storageBucket: 'salahtrackerbybasit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Md3fYbkFVLgYdnQ2QxKlvxdGir1Bz5o',
    appId: '1:580119553329:android:71423515150422e6657c10',
    messagingSenderId: '580119553329',
    projectId: 'salahtrackerbybasit',
    storageBucket: 'salahtrackerbybasit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx1tJj4DH1Kod-q69VpSm-WP1IqjDijTE',
    appId: '1:580119553329:ios:ea956d43e77931ed657c10',
    messagingSenderId: '580119553329',
    projectId: 'salahtrackerbybasit',
    storageBucket: 'salahtrackerbybasit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx1tJj4DH1Kod-q69VpSm-WP1IqjDijTE',
    appId: '1:580119553329:ios:ea956d43e77931ed657c10',
    messagingSenderId: '580119553329',
    projectId: 'salahtrackerbybasit',
    storageBucket: 'salahtrackerbybasit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV2k4x5WsQkh6-kMjJmySJ185YFFM1afg',
    appId: '1:580119553329:web:b56ec2fe99cd1225657c10',
    messagingSenderId: '580119553329',
    projectId: 'salahtrackerbybasit',
    authDomain: 'salahtrackerbybasit.firebaseapp.com',
    storageBucket: 'salahtrackerbybasit.firebasestorage.app',
  );
}
